### PR TITLE
Tournament and UC Fixtures

### PR DESCRIPTION
**Pull request by Joe2k**
For #116

### CODE REVIEW

**Comment by punchagan** [comment]
This is nice. It would be nice if you can add a bash script `scripts/update-sample-data` or something which dumps the fixtures and calls the email fixer.

**Comment by punchagan** [comment]
(accidentally closed it)

**Comment by punchagan** [comment]
@SibiAkkash can you test this PR and confirm that it works for you and has everything you need for #118 ?

**Comment by SibiAkkash** [comment]
> @SibiAkkash can you test this PR and confirm that it works for you and has everything you need for #118 ?

Hi @punchagan, @Joe2k there is test data now, but there is some proxy issue that i'm facing with the frontend.

The fetch call is being made to `localhost:3000/api/tournaments` instead of port 8000. I checked the `webpack.config.js` file, it seems to be setup correctly to route `/api/*` to `http://localhost:8000/api/*`

image

Trying to diagnose what's happening here

**Comment by Joe2k** [comment]
Haha everyone having same problem. Downgrade your node to 16.X and the problem will go away

Do mention this in readme when in your PR if possible

**Comment by SibiAkkash** [comment]
> Haha everyone having same problem. Downgrade your node to 16.X and the problem will go away
> 
> Do mention this in readme when in your PR if possible

Oh lol, let me check after downgrade

**Comment by punchagan** [comment]
> Do mention this in readme when in your PR if possible

I would prefer adding a constraint to the `package.json`. 

```
  "engines" : { 
    "node" : ">=16.0.0 <17.0.0"
  }
```

**Comment by punchagan** [comment]
> Is it a good idea to dockerize the dev env so we don't face these issues ?

Sure, we already have a deployment Docker setup. It should be possible to tweak it slightly for a dev env. If you'd like to contribute that, please do so! :)

**Comment by SibiAkkash** [comment]
> > Is it a good idea to dockerize the dev env so we don't face these issues ?
> 
> Sure, we already have a deployment Docker setup. It should be possible to tweak it slightly for a dev env. If you'd like to contribute that, please do so! :)

I'll do this, haven't setup docker files before though ;) !

**Comment by SibiAkkash** [comment]
> > > Do mention this in readme when in your PR if possible
> > 
> > 
> > I would prefer adding a constraint to the `package.json`.
> > ```
> >   "engines" : { 
> >     "node" : ">=16.0.0 <17.0.0"
> >   }
> > ```
> 
> @SibiAkkash since you are running on a new node version, right now... you might be able to quickly send a PR to add this constraint to `package.json` to prevent these errors. We can look into the docker dev env setup, later.
> 
> https://docs.npmjs.com/cli/v10/configuring-npm/package-json#engines

Raised a PR, but facing some linting issues in the workflow

**Comment by punchagan** [comment]
I think restricting `node` version isn't the right fix, since it would make it harder for developers to setup their dev env. The [bug we are running into](https://github.com/chimurai/http-proxy-middleware#nodejs-17-econnrefused-issue-with-ipv6-and-localhost-705) with node > 17 is that IPv6 is given a higher preference than IPv4 and Django by default doesn't run on IPv6. 

@SibiAkkash Can you verify that changing the proxy configuration in webpack.config.js to the following (replace `localhost` with `127.0.0.1`) works for you, with Node 18? In that case, can you submit a PR to that effect? Thanks!

```json
    proxy: {
      "/api": "http://127.0.0.1:8000",
      "/admin": "http://127.0.0.1:8000",
      "/static": "http://127.0.0.1:8000",
      "/uploads": "http://127.0.0.1:8000"
    }
```

**Comment by SibiAkkash** [comment]
> @SibiAkkash can you test this PR and confirm that it works for you and has everything you need for #118 ?

@Joe2k can you add some sample Live tournaments to the json file ? Thanks

**Comment by SibiAkkash** [comment]
> @SibiAkkash can you test this PR and confirm that it works for you and has everything you need for #118 ?

I've added some dummy events in my local db, to test for Live events showing up before all other events. This is enough for #118.

**Pull request merged**
