### PR TITLE
Improve tournament team view

### LINKED ISSUE #105: Improve the tournament team view
- Show the team as the first team always
- Make the team name of the other team clickable

### PR DESCRIPTION
**Pull request by SibiAkkash**
Fixes #105 

Previously this was the view
callahans_old_view

After this change:
image

The opponent team name is clickable

### CODE REVIEW

**Comment by Joe2k** [comment]
Awesomee! 

Thanks for destructuring the TournamentMatch to a new component! We can reuse that component in Tournament Schedule page as well and remove redundant code

**Comment by SibiAkkash** [comment]
> Awesomee!
> 
> Thanks for destructuring the TournamentMatch to a new component! We can reuse that component in Tournament Schedule page as well and remove redundant code

While using this component in the tournament schedule page, we'd want both team names to be clickable right ? Right now, only the other team (opponent of current team page) name would be clickable

**Comment by Joe2k** [comment]
Yep yep so basically you can default `currentTeamNo` as 1 and `opponentTeamNo ` as 2 if they are not passed and yes need to take care of both team names being clickable

**Comment by SibiAkkash** [comment]
> Yep yep so basically you can default `currentTeamNo` as 1 and `opponentTeamNo ` as 2 if they are not passed and yes need to take care of both team names being clickable

done

**Comment by Joe2k** [comment]
Nice. But I was also referring to TournamentSchedule file where you can refactor and just use TournamentMatch. See if you can find and do it. If not I will do it after its merged no issues @SibiAkkash

**Comment by SibiAkkash** [comment]
> Nice. But I was also referring to TournamentSchedule file where you can refactor and just use TournamentMatch. See if you can find and do it. If not I will do it after its merged no issues @SibiAkkash

Yeah I can see it in the TournamentSchedule component, I'll refactor it to use the match component. Should I do the refactor as part of this PR ?

**Comment by Joe2k** [comment]
I think you can.. @punchagan should be fine to do it along with this PR right?

**Comment by punchagan** [comment]
Yes, It would be nice to do it in this PR.

**Comment by SibiAkkash** [comment]
> Yes, It would be nice to do it in this PR.

done :)

**Pull request merged**
