### PR TITLE
Tournament All in One

### PR DESCRIPTION
**Pull request by Joe2k**
Tried to make commits atomic :P @punchagan

### CODE REVIEW

**Comment by punchagan** [comment]
Thanks a lot for working on this, @Joe2k! I've tried to review it, but haven't been able to fully review the logic you have implemented, yet. 

I've cleaned up the commits to try and make them more self-contained and [coherent](https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.html). Also, I've tried to get rid of so many migrations in the PR to a single one. I've pushed all these changes into a `feature-tournament` branch, that you can try and let me know what you think. (It looks like the create tournament is a little broken in the last commit of this PR?)

**Comment by Joe2k** [comment]
Ahh didnt get this _create tournament is a little broken in the last commit of this PR_
Anything you see is broken?

**Comment by punchagan** [comment]
> Anything you see is broken?

Oh, nevermind. There was no feedback from the tournament creation UI, and tournament already existed when I tried to create twice, etc...

**Comment by Joe2k** [comment]
Oh yeah lol if it exists i send a 400 but dont handle it in UI

**Comment by punchagan** [comment]
Closing in favor of #100. But, you could've just updated this branch to be in sync with the other one.. and force pushed here. :)

**Pull request closed without merging**
