### PR TITLE
Show team roles in validation and roster page

### PR DESCRIPTION
**Pull request by Joe2k**
For #157

### CODE REVIEW

**Comment by Joe2k** [comment]
Screenshot 2023-11-24 at 6 37 05 PM
Screenshot 2023-11-24 at 6 37 10 PM
Screenshot 2023-11-24 at 6 37 35 PM

**Comment by punchagan** [comment]
If a player is also a coach, should we show them in both the players list and the non-players list? (on validate roster page?)
And on the team page, showing the Coach label alone doesn't clarify that they were a player too.

**Comment by Joe2k** [comment]
On validation page it will come in both player and non-player list.. Which is good I think

In team Page then we can have 2 sections.. 1 for players and 1 for non-players just like validation page then?

**Comment by punchagan** [comment]
> In team Page then we can have 2 sections.. 1 for players and 1 for non-players just like validation page then?

I think that makes sense.

**Review by SibiAkkash — APPROVED** [review]

**Comment by Joe2k** [comment]
Screenshot 2023-12-06 at 5 01 40 PM
@punchagan made changes as we discussed above

**Pull request merged**
