### PR TITLE
Reverse chronological ordering for tournaments

### LINKED ISSUE #118: Sort tournaments reverse chronologically on the tournament page
Currently live or the most recent tournaments should be shown before older tournaments

### PR DESCRIPTION
**Pull request by SibiAkkash**
Fixes #118

### CODE REVIEW

**Comment by punchagan** [comment]
@SibiAkkash can you rebase this branch against the latest `main`? 

The docs here would be helpful: https://zulip.readthedocs.io/en/latest/git/pull-requests.html

You can ask for help on Zulip, if you need more help!

**Comment by AnishKacham** [comment]
We could also sort it in the backend itself.
will need just an alteration on the return statement over here:
 https://github.com/india-ultimate/hub/blob/a9848941b7e7644eed1b7132a0d7b52cebd48fd1/server/api.py#L846
 https://stackoverflow.com/questions/50318367/django-order-queryset-by-onetoonefield
Opinions?
@punchagan @SibiAkkash

**Comment by SibiAkkash** [comment]
> We could also sort it in the backend itself. will need just an alteration on the return statement over here:
> 
> https://github.com/india-ultimate/hub/blob/a9848941b7e7644eed1b7132a0d7b52cebd48fd1/server/api.py#L846
> 
> 
> https://stackoverflow.com/questions/50318367/django-order-queryset-by-onetoonefield
> Opinions?
> @punchagan @SibiAkkash

I thought of this, but wasn't sure if we'd need this reverse ordering by default. I can make the change in the API if that's fine

**Comment by punchagan** [comment]
> I thought of this, but wasn't sure if we'd need this reverse ordering by default. I can make the change in the API if that's fine

Yeah, I think we can make the change in the API since it makes sense to get tournaments ordered reverse chronologically, in most cases.  Nice catch, @AnishKacham :+1:

**Pull request closed without merging**
