### PR TITLE
ui: add breadcrumbs and update dashboard for mobile view

### PR DESCRIPTION
**Pull request by Joe2k**
For #80 

Screenshot 2023-09-02 at 10 25 18 AM
Screenshot 2023-09-02 at 10 25 43 AM
Screenshot 2023-09-02 at 10 25 56 AM

### CODE REVIEW

**Comment by punchagan** [comment]
Can you post before pics too, if it's not too much to ask for? Thanks @Joe2k !

**Comment by Joe2k** [comment]
@punchagan 
Screenshot 2023-09-02 at 7 01 56 PM
Screenshot 2023-09-02 at 7 02 04 PM

yep sure

**Comment by punchagan** [comment]
Merged manually after being pedantic about making the commits more atomic. :)

**Comment by punchagan** [comment]
Thanks for cleaning this up, @Joe2k ! :pray:

**Pull request closed without merging**
