### PR TITLE
Matching match component colors to the Match card

### PR DESCRIPTION
**Pull request by SibiAkkash**

### CODE REVIEW

**Comment by SibiAkkash** [comment]
The first commit here depends on the db migration from the other PR. So that PR would have to merged first i think. Better way would be to do stacked PRs i think, here i've cherry-picked the commits on current main

**Comment by Joe2k** [comment]
So here you are still using match.name right.. So then well have merge the match name generation and all that from the other pr as well

**Comment by SibiAkkash** [comment]
Yeah using match.name here, so we have to merge that pr first

**Comment by SibiAkkash** [comment]
How do you feel about coloring the buttons red, green, gray in the team page ? I think it can just be blue in teams page ?
### Team page

image
image


### Schedule page

image
image

**Comment by Joe2k** [comment]
Then its better to rebase that old pr only and merge?

**Comment by SibiAkkash** [comment]
> Then its better to rebase that old pr only and merge?

you mean merging that pr to main, then rebasing this pr to new main right ? Yeah that's the way i think

**Comment by Joe2k** [comment]
Hmm so yeah filled color button is a bit weird.. Can we have the border coloured button instead for all the admin buttons? Just like the view spirit scores button? That should be nice and we can red green grey in that i think. What you think?

**Comment by SibiAkkash** [comment]
> Hmm so yeah filled color button is a bit weird.. Can we have the border coloured button instead for all the admin buttons? Just like the view spirit scores button? That should be nice and we can red green grey in that i think. What you think?

hmm let me see how it looks

**Comment by Joe2k** [comment]
Yeah but that PR cant be merged currently right? Cause its conflicting with the main?

**Comment by SibiAkkash** [comment]
> Yeah but that PR cant be merged currently right? Cause its conflicting with the main?

yeah i'll rebase and push that. I'm using that pr to test the colors, because this PR doesn't have match names generated lol

**Comment by SibiAkkash** [comment]
> Hmm so yeah filled color button is a bit weird.. Can we have the border coloured button instead for all the admin buttons? Just like the view spirit scores button? That should be nice and we can red green grey in that i think. What you think?

image 
image

**Comment by punchagan** [comment]
Alright, let's close this PR to not fork the discussion. Sorry for the confusion. :)

**Pull request closed without merging**
