### PR TITLE
Show spirit scores along with results in match card

### LINKED ISSUE #120: Include spirit scores in the team view
The team view makes it easy to see all the scores of a team, in the tournament. A similar view for spirit scores would be nice. We could also include spirit scores in the same list...

Image

We currently show a button that links to the spirit scores, but we might be able to show a summary view of the spirit scores too. (See [windmill site](https://www.windmilltournament.com/legacy), for instance)

Image

### PR DESCRIPTION
**Pull request by Joe2k**
fixes #120 

Screenshot 2023-11-24 at 11 01 37 PM

### CODE REVIEW

**Comment by Joe2k** [comment]
Screenshot 2023-11-24 at 11 19 48 PM

Also added tabs in the team page for better accessibility and UX

**Comment by Joe2k** [comment]
fixes #202 as well
Screenshot 2023-11-24 at 11 41 19 PM

**Comment by punchagan** [comment]
Woah! @Joe2k is on fire!

**Comment by punchagan** [comment]
> Screenshot 2023-11-24 at 11 19 48 PM

We could use full scores like 2;2;2;2;2 instead of 10?

**Comment by Joe2k** [comment]
> We could use full scores like 2;2;2;2;2 instead of 10?

Hmm not so sure on that as it will take more space... and since we anyway showing the detailed split when the user clicks on button it should be fine?

Also people wont know what is the order of criteria when we just put 2;2;2;2;2 and might just be confusing i think

**Comment by punchagan** [comment]
I think players would know the order, but fair enough that it's just a click away.  May be we can make the spirit scores themselves clickable instead of the extra button to see Scores/MVP/MSP?

**Comment by Joe2k** [comment]
Yeah, but then how we'll show/make user know that its clickable?

**Comment by punchagan** [comment]
> Yeah, but then how we'll show/make user know that its clickable?

Maybe use an arrow or make it like a button or something. I'm not sure. @SibiAkkash might have ideas.

**Comment by SibiAkkash** [comment]
> @SibiAkkash Any thoughts on this? If not I think we can merge this for now and think later..

The "Spirit Scores, MVP, MSP" button could be renamed to "Spirit : 10 - 10".
Or, like punch was saying we could have a small badge
Like the below pic, we could have "Spirit" in blue, the score "10-10" in gray, and add an arrow to indicate clickability
image

**Comment by Joe2k** [comment]
Updated @SibiAkkash @punchagan 
Screenshot 2023-12-03 at 1 46 27 PM
Screenshot 2023-12-03 at 1 46 36 PM

**Review by SibiAkkash — APPROVED** [review]

**Comment by Joe2k** [comment]
Rebased and Pushed... This is also ready to be reviewed and merged
@punchagan

**Pull request merged**
