### PR TITLE
Enter spirit scores for caps / spirit caps

### PR DESCRIPTION
**Pull request by Joe2k**
for #114

### CODE REVIEW

**Comment by SibiAkkash** [comment]
Nicee, I'll review soon !

**Comment by Joe2k** [comment]
@punchagan Before was pointing to diff branch. So here now locally Ill rebase to main and then push right?

**Comment by punchagan** [comment]
> @punchagan Before was pointing to diff branch. So here now locally Ill rebase to main and then push right?

ideally, yes. but, I can do the rebase while I review/merge too.

**Comment by Joe2k** [comment]
Squared logo + tournaments in navbar screenshot
Screenshot 2023-11-14 at 5 03 28 PM

**Pull request merged**
