### PR TITLE
prometheus: Add more app level metrics

### PR DESCRIPTION
**Pull request by Joe2k**

### CODE REVIEW

**Comment by Joe2k** [comment]
Had to add ignore type due to below issue
`server/models.py:36: error: Unsupported dynamic base class "ExportModelOperationsMixin"  [misc]`

**Comment by punchagan** [comment]
What's the motivation for this change? What are we trying to track here?

**Comment by Joe2k** [comment]
Wanna track api level stuff.. Like for passkeys and also for Phonepe transactions how many going through etc

**Comment by Joe2k** [comment]
Will help to track lot of other things as well in future when razorpay and all comes

**Comment by Joe2k** [comment]
Also we would have known if a match got deleted when we were merging all people :P

Basically nothing wrong with having more metrics and visibility right xD

**Comment by Joe2k** [comment]
merge pls 🙏

**Review by SibiAkkash — APPROVED** [review]

**Pull request merged**
