### PR TITLE
email-otp: Add email type to input and validate email

### PR DESCRIPTION
**Pull request by Joe2k**
@punchagan review and mergee :p lotta peeps having this prob xD

### CODE REVIEW

**Review by SibiAkkash — APPROVED** [review]

**Comment by punchagan** [comment]
I know there are lot of users, but if a user already has an account with a capitalized email, they will no longer be able to login. Is that better than the situation we have now? If yes, I can do this. But, I think being able to login to both the accounts, until we prevent such account creation might be better?

**Comment by Joe2k** [comment]
Ahh yep truee.. esp with regionals nearby if users get logged out its bad.
Cool lets wait and do full solution

**Comment by punchagan** [comment]
Closing in favor of #168

**Comment by Joe2k** [comment]
@punchagan Can we open and merge this once you merge duplicate accounts in Prod?

**Comment by punchagan** [comment]
Deployed! Thanks for the nudge.

**Pull request merged**
