### PR TITLE
Update fixtures with field entities

### PR DESCRIPTION
**Pull request by SibiAkkash**
i've dumped that data with the latest migrations.
```bash
python manage.py dumpdata --exclude=contenttypes > server/fixtures/sample_data.json
```

@Joe2k: can you check if loading this fixture works and merge ?

### CODE REVIEW

**Comment by punchagan** [comment]
We have a script `scripts/update-sample-data.sh`. Is there a reason that you didn't use that? :)

**Comment by SibiAkkash** [comment]
Oh i didn't see that script ;) I'll use that

**Comment by punchagan** [comment]
May be use an empty DB and try to see if the load works, and allows a new dev to start working with the dumped DB? If you can share the full error, we can dig into it.

**Comment by SibiAkkash** [comment]
yeah i did try in an empty db, i'll share the errors

**Comment by SibiAkkash** [comment]
Commands i ran
```bash
./scripts/update-sample-data.sh

rm db.sqlite3
python manage.py migrate
python manage.py loaddata server/fixtures/sample_data.json
```

error: 
django.db.utils.IntegrityError: Problem installing fixture '/home/sibi/dev/india_ultimate_hub/server/fixtures/sample_data.json': Could not load contenttypes.ContentType(pk=25): UNIQUE constraint failed: django_content_type.app_label, django_content_type.model

**Pull request merged**
