### PR TITLE
guardianship: Fix age validation

### PR DESCRIPTION
**Pull request by Joe2k**
For cases where player is 18+ but still has guardian.. Currently we are still not allowing them to sign but rather ask their guardian to sign

### CODE REVIEW

**Comment by Joe2k** [comment]
We are already doing that now.. api.py line 616.. i think that issue was before we implemented this check

**Review by SibiAkkash — DISMISSED** [review]

**Comment by SibiAkkash** [comment]
oh some tests are failing

**Comment by Joe2k** [comment]
@SibiAkkash fixed now

**Comment by punchagan** [comment]
> oh some tests are failing

yeah, looks like the code has been written with only minor players in mind? 

Looks reasonable to me to allow guardian (if player was previously minor) or the player themselves to sign the waiver (if they are no longer minor)... 

It may be useful to let players "unlink" guardians if they are no longer minor; Doing it automatically could be confusing in some edge cases, but could be nice to do generally?

**Comment by Joe2k** [comment]
Yeah so now once they are 18+ im not even sending the guardianship is response on Player schema.. so thats equal to unlink only.. but just that we are still having that previous data

**Comment by punchagan** [comment]
Looks good to me, with a quick look!

**Comment by Joe2k** [comment]
Resolved and fixed the tests.. @SibiAkkash

**Review by SibiAkkash — APPROVED** [review]

**Pull request merged**
