### PR TITLE
Breadcrumb magic & Scroll to top

### LINKED ISSUE #106: Improve the magic to generate the breadcrumb on tournament pages
The breadcrumb generation currently uses the event slug, which may not always follow the pattern. 

Image

We could directly use the event title. And if required strip the NCS + year prefix, if we really need to make the breadcrumb shorter.

### LINKED ISSUE #207: Add a "go to top" button in tournament schedule page
Adding such a button would avoid having to scroll a long way up to get to the schedule

### PR DESCRIPTION
**Pull request by Joe2k**
fixes #106 
fixes #207 
Screenshot 2023-12-05 at 10 16 12 AM
Screenshot 2023-12-05 at 10 16 21 AM

Screenshot 2023-12-05 at 10 17 25 AM

### CODE REVIEW

**Comment by Joe2k** [comment]
@SibiAkkash Fixed the schedule page no matches on a day bug... Pls review and approve this PR
Screenshot 2023-12-05 at 10 07 42 PM

**Comment by SibiAkkash** [comment]
Nice, could be a quick fix for now I think. Maybe later we can remove the first day itself completely, if no matches on the "start date"

**Comment by SibiAkkash** [comment]
> @SibiAkkash Fixed the schedule page no matches on a day bug... Pls review and approve this PR
> Screenshot 2023-12-05 at 10 07 42 PM
> 

Nice, will review tmrw ?

**Comment by Joe2k** [comment]
yep cool

**Pull request merged**
