### PR TITLE
Allow addition of tournament admins

### PR DESCRIPTION
**Pull request by Joe2k**

### CODE REVIEW

**Comment by Joe2k** [comment]
@punchagan @SibiAkkash This is all the stuff to fix the bugs in current code. Please do review and merge

**Comment by SibiAkkash** [comment]
Of course it was the schema change commit 🙈

**Comment by SibiAkkash** [comment]
Thanks for fixing these bugs @Joe2k ❤️, i'll take more care before pushing commits like those 👀

**Comment by Joe2k** [comment]
Yep I also made some mistakes.. We need to be more careful now that a lot of things are involved and do proper testing for each PR.
Lesson to be learnt

**Comment by SibiAkkash** [comment]
> Yep I also made some mistakes.. We need to be more careful now that a lot of things are involved and do proper testing for each PR. Lesson to be learnt

Agree !

**Comment by SibiAkkash** [comment]
> > Yep I also made some mistakes.. We need to be more careful now that a lot of things are involved and do proper testing for each PR. Lesson to be learnt
> 
> Agree, maybe should start writing more UI tests

**Comment by Joe2k** [comment]
@punchagan have added tournament admins to this PR.. Let me know once deployed and ill add shubham to this and test with him and then shift all TDs and Sds to this

**Comment by punchagan** [comment]
Merged the bug-fix commits.

**Comment by punchagan** [comment]
Closes #99

**Pull request merged**
