### PR TITLE
Show some fields as broadcast-ed fields

### PR DESCRIPTION
**Pull request by SibiAkkash**
Tasks

- [x] alert if name is repeated while creating a field
- [x] API endpoint to edit a field
- [x] edit fields in tournament manager

https://github.com/india-ultimate/hub/assets/39093537/42570e9d-2227-4f48-94dc-b45b58ac0cea

### CODE REVIEW

**Review by Joe2k — CHANGES_REQUESTED** [review]

**Comment by Joe2k** [comment]
Also send SS of tournament manager changes?

**Comment by Joe2k** [comment]
Also we would need update field API to add broadcasting to existing field like for current nationals

**Comment by Joe2k** [comment]
Great work btw.. Really nice data modelling <3

**Comment by SibiAkkash** [comment]
> Also send SS of tournament manager changes?

image

**Comment by SibiAkkash** [comment]
> Also we would need update field API to add broadcasting to existing field like for current nationals

So i'll add an edit button to the fields, in tournament manager ?

**Comment by SibiAkkash** [comment]
### Dialog focus Issue

When `showModal()` is used to open a `<dialog>`, it displays a modal dialog. A modal dialog traps focus to the dialog contents only, other elements on the screen don't get focus. 

 *Modal dialog boxes interrupt interaction with the rest of the page being inert, while non-modal dialog boxes allow interaction with the rest of the page*. - [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog)
 
Only modal dialogs get the `::backdrop` pseudo-element.

When directly using `props.fields` in the `CreatedFields` component, i noticed some focus issues with the dialog. 

```jsx
<For each={props.fields}>
```

When i opened the edit dialog, went out of `focus` (interacting with devtools, or a different tab) and `focused` the page again, the `<dialog>` would render as a non-modal dialog. That is, the backdrop styles disappear, it appears in the regular flow of the document, other UI elements can get focus without closing the dialog etc...

*Dialogs that are displayed using the `open` attribute are non-modal.* - [HTML-only dialog](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog#html-only_dialog)

#### Observations

When i disabled `refetchOnWindowFocus` for the fields query, this dialog losing focus thing didn't happen.

But the problem persisted when i submitted the form in the modal. On submit, the edit mutation would run, and this would invalidate the fields query, and trigger a re-fetch When the mutation would complete, the dialog would lose focus again.

As i was passing the present fields as a prop to the form, for validation purposes, i think this too triggered a re-render of sorts. (since re-renders don't really happen in solid, not sure what exactly is happening here. A un-mount/re-mount ??)

```jsx
<EditFieldForm
	alreadyPresentFields={props.fields}
/>
```

*Interestingly, when i wrapped `props.fields` in a separate signal, and used that in the component, these focus issues went away*

```jsx
const [fields, setFields] = createSignal();

createEffect(() => setFields(props.fields));

return (
	<For each={fields()}>
		...
		<EditFieldForm
			alreadyPresentFields={fields()}
		/>
		...
	</For>
)

```

#### My guess on what's happening

When the `<dialog>` is first opened with `showModal()`, the `open` attribute is set on the `<dialog>`. When focus goes away from the tab and comes back, something is triggering a re-render of the DOM. This time, the `<dialog>`  already has the `open` attribute on it (from when we first opened the dialog). So, now the `<dialog>` becomes non-modal, since its rendered with the open attribute already on it.

So i think the querying/mutations are messing with the focus of the page and its related events on the browser.

> The `focus` event has many pitfalls, as it's triggered in the following cases:
> - Navigating between DevTools and the app.
> - When closing an `alert` or `confirm` dialog.
> - File upload dialogs.
> - When interacting with an iframe.

From: [Does it still make sense to refetch queries on "focus" by default?](https://github.com/TanStack/query/discussions/4797)

- [Input type=file dialogue triggers windows focus refetch](https://github.com/TanStack/query/issues/2960)
- [infinite loop refetch when call window.alert inside request](https://github.com/TanStack/query/issues/2868)

Maybe something can be done with [Custom window focus event](https://github.com/TanStack/query/issues/2960)

---

So when using dialogs, i think we'd have to wrap query outputs in a separate signal. I'm not sure about the root cause, this is all i've found on this... Slightly long rabbit hole for a small issue, i know 🙈

@Joe2k @punchagan

**Review by Joe2k — APPROVED** [review]

**Pull request merged**
